name: store_amount_prediction
dependencies:
  - python=3.7
  - r::rpy2==2.9.4
  - jupyter
  - notebook
  - pip
  - pip:
    - tzlocal
    - numpy==1.19.1
    - pandas==0.25.1
    - pmdarima==1.5.3
    - statsmodels==0.11.1
    - seaborn==0.11.0
    - tqdm==4.51.0